### ISSUE TITLE
Modelos de Pesquisa

### ISSUE THREAD

**Issue by gutobova** [gutobova/digital_garden#1]
# Objetivo
Os modelos de pesquisa servirao para guiar os `pesquisadores` na estuturacao da pesquisa para abastecer os `desenvolvedores` com a documentacao relevante ao tipo do projeto.
# Tasks
- [ ]  Definir os modelos de pesquisa
- [ ]  criar a documentacao e manuais de ultilizacao de cada um deles

>[!NOTE]
>Documentation according to [this page](https://github.com/gutobova/digital_garden/wiki/Modelos-de-Pesquisa)

**Comment by gutobova** [comment]
# Objetivo
Os modelos de pesquisa servirao para guiar os `pesquisadores` na estuturacao da pesquisa para abastecer os `desenvolvedores` com a documentacao relevante ao tipo do projeto.
# Tasks
- [ ]  Definir os modelos de pesquisa
- [ ]  criar a documentacao e manuais de ultilizacao de cada um deles
